In [5]:
import pandas as pd
df = pd.read_csv("mars-2014-complete.csv",encoding="latin1", sep=";", low_memory=False)
df.head()

,lib_mrq,lib_mod_doss,lib_mod,dscom,cnit,tvv,cod_cbr,hybride,puiss_admin_98,puiss_max,...,masse_ordma_min,masse_ordma_max,champ_v9,date_maj,Carrosserie,gamme,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,ALFA-ROMEO,159,159,159 1750 Tbi (200ch),M10ALFVP000G340,939AXN1B52C,ES,non,12,147,...,1505,1505,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
1,ALFA-ROMEO,159,159,159 1750 Tbi (200ch),M10ALFVP000H341,939BXN1B53C,ES,non,12,147,...,1555,1555,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
2,ALFA-ROMEO,159,159,159 2.0 JTDm (136ch),M10ALFVP000E302,939AXR1B64,GO,non,7,100,...,1565,1565,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
3,ALFA-ROMEO,159,159,159 2.0 JTDm (136ch),M10ALFVP000F303,939AXR1B64B,GO,non,7,100,...,1565,1565,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
4,ALFA-ROMEO,159,159,159 2.0 JTDm (170ch),M10ALFVP000G304,939AXS1B66,GO,non,9,125,...,1565,1565,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN

In [15]:
# la taille de dataset
df.shape

(55044, 30)

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55044 entries, 0 to 55043
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lib_mrq            55044 non-null  str
 1   lib_mod_doss       55044 non-null  str
 2   lib_mod            55044 non-null  str
 3   dscom              55044 non-null  str
 4   cnit               55044 non-null  str
 5   tvv                55044 non-null  str
 6   cod_cbr            55044 non-null  str
 7   hybride            55044 non-null  str
 8   puiss_admin_98     55044 non-null  int64
 9   puiss_max          55044 non-null  str
 10  typ_boite_nb_rapp  55044 non-null  str
 11  conso_urb          55001 non-null  str
 12  conso_exurb        55001 non-null  str
 13  conso_mixte        55010 non-null  str
 14  co2                55010 non-null  float64
 15  co_typ_1           54886 non-null  str
 16  hc                 9773 non-null   str
 17  nox                54886 non-null  str
 18  hcnox              45156 non-null  str
 19  ptcl               52366 non-null  str
 20  masse_ordma_min    55044 non-null  int64
 21  masse_ordma_max    55044 non-null  int64
 22  champ_v9           54983 non-null  str
 23  date_maj           3247 non-null   str
 24  Carrosserie        55044 non-null  str
 25  gamme              55044 non-null  str
 26  Unnamed: 26        0 non-null      float64
 27  Unnamed: 27        0 non-null      float64
 28  Unnamed: 28        0 non-null      float64
 29  Unnamed: 29        0 non-null      float64
dtypes: float64(5), int64(3), str(22)
memory usage: 12.6 MB

In [22]:
# presence des nulls
df.isnull().sum()

lib_mrq                  0
lib_mod_doss             0
lib_mod                  0
dscom                    0
cnit                     0
tvv                      0
cod_cbr                  0
hybride                  0
puiss_admin_98           0
puiss_max                0
typ_boite_nb_rapp        0
conso_urb               43
conso_exurb             43
conso_mixte             34
co2                     34
co_typ_1               158
nox                    158
hcnox                 9888
ptcl                  2678
masse_ordma_min          0
masse_ordma_max          0
champ_v9                61
date_maj             51797
Carrosserie              0
gamme                    0
dtype: int64

In [12]:
# afficher uniquement celle qui ont la presence des valeurs nulles
df.isnull().sum()[df.isnull().sum() > 0]

conso_urb         43
conso_exurb       43
conso_mixte       34
co2               34
co_typ_1         158
hc             45271
nox              158
hcnox           9888
ptcl            2678
champ_v9          61
date_maj       51797
Unnamed: 26    55044
Unnamed: 27    55044
Unnamed: 28    55044
Unnamed: 29    55044
dtype: int64

In [18]:
# supprimer des variables NaN : unnamed 26-29 , hc 
df = df.drop(columns=[
    'Unnamed: 26',
    'Unnamed: 27',
    'Unnamed: 28',
    'Unnamed: 29',
    'hc'
])

In [21]:
#verifier des types et convertir en numerique si necessaire
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55044 entries, 0 to 55043
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lib_mrq            55044 non-null  str
 1   lib_mod_doss       55044 non-null  str
 2   lib_mod            55044 non-null  str
 3   dscom              55044 non-null  str
 4   cnit               55044 non-null  str
 5   tvv                55044 non-null  str
 6   cod_cbr            55044 non-null  str
 7   hybride            55044 non-null  str
 8   puiss_admin_98     55044 non-null  int64
 9   puiss_max          55044 non-null  str
 10  typ_boite_nb_rapp  55044 non-null  str
 11  conso_urb          55001 non-null  str
 12  conso_exurb        55001 non-null  str
 13  conso_mixte        55010 non-null  str
 14  co2                55010 non-null  float64
 15  co_typ_1           54886 non-null  str
 16  nox                54886 non-null  str
 17  hcnox              45156 non-null  str
 18  ptcl               52366 non-null  str
 19  masse_ordma_min    55044 non-null  int64
 20  masse_ordma_max    55044 non-null  int64
 21  champ_v9           54983 non-null  str
 22  date_maj           3247 non-null   str
 23  Carrosserie        55044 non-null  str
 24  gamme              55044 non-null  str
dtypes: float64(1), int64(3), str(21)
memory usage: 10.5 MB

In [26]:
# convertir les types en numerique
colonnes_numeriques = [
    'puiss_max',
    'conso_urb',
    'conso_exurb',
    'conso_mixte',
    'nox',
    'hcnox',
    'ptcl',
    "co_typ_1"
]

for col in colonnes_numeriques:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [27]:
# verifier les types convertis:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 55044 entries, 0 to 55043
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lib_mrq            55044 non-null  str
 1   lib_mod_doss       55044 non-null  str
 2   lib_mod            55044 non-null  str
 3   dscom              55044 non-null  str
 4   cnit               55044 non-null  str
 5   tvv                55044 non-null  str
 6   cod_cbr            55044 non-null  str
 7   hybride            55044 non-null  str
 8   puiss_admin_98     55044 non-null  int64
 9   puiss_max          54851 non-null  float64
 10  typ_boite_nb_rapp  55044 non-null  str
 11  conso_urb          6124 non-null   float64
 12  conso_exurb        4545 non-null   float64
 13  conso_mixte        6496 non-null   float64
 14  co2                55010 non-null  float64
 15  co_typ_1           0 non-null      float64
 16  nox                30 non-null     float64
 17  hcnox              11 non-null     float64
 18  ptcl               18274 non-null  float64
 19  masse_ordma_min    55044 non-null  int64
 20  masse_ordma_max    55044 non-null  int64
 21  champ_v9           54983 non-null  str
 22  date_maj           3247 non-null   str
 23  Carrosserie        55044 non-null  str
 24  gamme              55044 non-null  str
dtypes: float64(9), int64(3), str(13)
memory usage: 10.5 MB

In [19]:
# la representation poderale des marques
df.describe()

       puiss_admin_98           co2  masse_ordma_min  masse_ordma_max
count    55044.000000  55010.000000     55044.000000     55044.000000
mean        10.551504    201.707035      2102.104553      2341.021801
std          5.126021     33.976278       294.731715       424.067895
min          1.000000     13.000000       825.000000       825.000000
25%          9.000000    193.000000      1982.000000      2075.000000
50%         10.000000    205.000000      2076.000000      2355.000000
75%         10.000000    216.000000      2246.000000      2709.000000
max         81.000000    572.000000      2760.000000      3094.000000

In [13]:
# determiner les variables categorielles et les stocker dans cat_data
cat_data = df.select_dtypes(include = 'O')
cat_data.head()

C:\Users\Laura\AppData\Local\Temp\ipykernel_8088\1205252930.py:2: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  cat_data = df.select_dtypes(include = 'O')

,lib_mrq_doss,lib_mod_doss,mrq_utac,mod_utac,dscom,cnit,tvv,energ,hybride,typ_boite_nb_rapp,champ_v9,date_maj
0,ALFA ROMEO,159,ALFA ROMEO,159,159 1750 Tbi (200ch),M10ALFVP000G340,939AXN1B52C,ES,non,M 6,715/2007*692/2008EURO5,juin-14
1,ALFA ROMEO,159,ALFA ROMEO,159,159 2.0 JTDm (170ch) ECO,M10ALFVP000U221,939AXP1B54C,GO,non,M 6,715/2007*692/2008EURO5,juin-14
2,ALFA ROMEO,159,ALFA ROMEO,159,159 2.0 JTDm (136ch),M10ALFVP000E302,939AXR1B64,GO,non,M 6,715/2007*692/2008EURO5,juin-14
3,ALFA ROMEO,159,ALFA ROMEO,159,159 2.0 JTDm (136ch),M10ALFVP000F303,939AXR1B64B,GO,non,M 6,715/2007*692/2008EURO5,juin-14
4,ALFA ROMEO,159,ALFA ROMEO,159,159 2.0 JTDm (170ch),M10ALFVP000G304,939AXS1B66,GO,non,M 6,715/2007*692/2008EURO5,juin-14

In [9]:
# afficher les modalités de variable dscom :
display(cat_data['dscom'].value_counts())

NameError: name 'cat_data' is not defined

In [15]:
# afficher les modalités de variable energ :
display(cat_data['energ'].value_counts())

energ
GO        12675
ES         6934
EH          546
GH          386
EE           90
GN           61
EL           56
ES/GN        52
GN/ES        36
ES/GP        21
GP/ES        21
FE            1
GL            1
Name: count, dtype: int64

decodage de type d'energi:
Code	Signification probable	Explication
GO	Gazole (Diesel)	            Le plus courant dans ton dataset
ES	Essence	                    Voitures essence classiques
EL	Électrique	                Véhicules 100% électriques
EH	Hybride essence	            Hybride essence (non rechargeable souvent)
GH	Hybride gazole	            Hybride diesel
EE	Électrique étendu / hybride 
    rechargeable électrique	    Selon bases françaises, souvent PHEV
GN	Gaz naturel (GNV)	        Gaz naturel pour véhicules
GP	GPL	                        Gaz de pétrole liquéfié
GL	GPL léger / variante rare	Très peu utilisé
FE	Flexfuel E85	            Bioéthanol (essence + éthanol)

In [16]:
# boite a vitesse typ_boite_nb_rapp
# afficher les modalités de variable typ_boite_nb_rapp :
display(cat_data['typ_boite_nb_rapp'].value_counts())

typ_boite_nb_rapp
A 7     9153
M 6     7371
A 8     1027
M 5      859
A 6      799
A 9      689
V 0      482
A 5      163
M 7       80
D 5       59
D 7       48
A 0       44
D 6       28
M 1       27
V .       24
A 4       20
A 1        3
N 0        3
V 1        1
Name: count, dtype: int64

Decodage des codes boite à vitesse:
M	Boîte manuelle
A	Boîte automatique
D	Boîte robotisée / double embrayage (type DSG, EDC…)
V	Variation continue (CVT)
N	Neutre / non renseigné / inconnu

In [17]:
# le modele du dossier lib_mod_doss
# afficher les modalités de variable typ_boite_nb_rapp :
display(cat_data['lib_mod_doss'].value_counts())

lib_mod_doss
CLASSE E             3104
CLASSE C             2955
SPRINTER             2697
VITO                 1026
CLASSE S              980
                     ...
CAYENNE S DIESEL        1
WRX                     1
JIMNY                   1
JETTA                   1
V60 HYBRID              1
Name: count, Length: 442, dtype: int64

In [ ]:
# nombre de modalité dans une variable lib_mod_doss
len(cat_data["lib_mod_doss"].unique())

442

In [23]:
# nombre de modalité ayant un faible poid:
(cat_data["lib_mod_doss"]
 .value_counts()
 .lt(10)
 .sum())

np.int64(249)

In [25]:
# taux des valeurs Nan par colonne
display(df["puiss_heure"].isna().mean() * 100)

np.float64(95.71360153256705)

In [21]:
display(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 20880 entries, 0 to 20879
Data columns (total 26 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lib_mrq_doss       20880 non-null  str
 1   lib_mod_doss       20880 non-null  str
 2   mrq_utac           20880 non-null  str
 3   mod_utac           20880 non-null  str
 4   dscom              20880 non-null  str
 5   cnit               20880 non-null  str
 6   tvv                20880 non-null  str
 7   energ              20880 non-null  str
 8   hybride            20880 non-null  str
 9   puiss_admin        20880 non-null  int64
 10  puiss_max          20824 non-null  float64
 11  puiss_heure        895 non-null    float64
 12  typ_boite_nb_rapp  20880 non-null  str
 13  conso_urb_93       20759 non-null  float64
 14  conso_exurb        20759 non-null  float64
 15  conso_mixte        20824 non-null  float64
 16  co2_mixte          20824 non-null  float64
 17  co_typ_1           20605 non-null  float64
 18  hc                 8897 non-null   float64
 19  nox                20605 non-null  float64
 20  hcnox              11735 non-null  float64
 21  ptcl               19170 non-null  float64
 22  masse_ordma_min    20880 non-null  int64
 23  masse_ordma_max    20880 non-null  int64
 24  champ_v9           20880 non-null  str
 25  date_maj           20880 non-null  str
dtypes: float64(11), int64(3), str(12)
memory usage: 4.1 MB

None