In [3]:
# Charger le dataset sauvegardé
import pandas as pd
X_test = pd.read_csv("../src/X_test_final.csv")
X_train = pd.read_csv("../src/X_train_final.csv")
y_test = pd.read_csv("../src/y_test.csv")
y_train = pd.read_csv("../src/y_train.csv")
X_test.head()

,puiss_max,conso_mixte,co_typ_1,nox,ptcl,masse_ordma_min,masse_ordma_max,lib_mrq_ASTON MARTIN,lib_mrq_AUDI,lib_mrq_BENTLEY,...,typ_boite_nb_rapp_A 9,typ_boite_nb_rapp_D 5,typ_boite_nb_rapp_D 6,typ_boite_nb_rapp_D 7,typ_boite_nb_rapp_M 5,typ_boite_nb_rapp_M 6,typ_boite_nb_rapp_M 7,typ_boite_nb_rapp_S 6,typ_boite_nb_rapp_V .,typ_boite_nb_rapp_V 0
0,100.0,8.0,0.078,0.224,0.001,2025,2075,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,120.0,8.1,0.087,0.275,0.000,2076,2185,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,120.0,7.3,0.046,0.197,0.000,2186,2355,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
3,120.0,7.7,0.175,0.226,0.001,2186,2350,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0
4,80.0,8.0,0.137,0.214,0.001,1976,2783,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0

In [16]:
#afficher dataset chargé

print(y_train.shape)
print(y_test.shape)

(44008,)
(11002,)

In [15]:
#afficher le type des datasets chargés

print(type(X_train))
print(type(X_test)) 
print(type(y_train))
print(type(y_test))

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
<class 'pandas.Series'>
<class 'pandas.Series'>

In [ ]:
# transformer les datasets y_train et y_test en vecteurs 1D

y_train = y_train.squeeze()
y_test = y_test.squeeze()

print(type(y_train))
print(y_train.shape)

<class 'pandas.Series'>
(44008,)

In [ ]:
# Colonnes à supprimer du dataset suite à la forte corrélation
cols_a_supprimer = [
    "co_typ_1",
    "conso_mixte",
    "nox"
]

X_train = X_train.drop(columns=cols_a_supprimer)
X_test = X_test.drop(columns=cols_a_supprimer)

In [18]:
#supprimer des marques:
cols_lib_mrq = X_train.filter(regex="^lib_mrq_").columns

X_train.drop(columns=cols_lib_mrq, inplace=True)
X_test.drop(columns=cols_lib_mrq, inplace=True)

In [19]:
print(X_train.columns.tolist())

['puiss_max', 'ptcl', 'masse_ordma_min', 'masse_ordma_max', 'cod_cbr_EH', 'cod_cbr_ES', 'cod_cbr_ES/GN', 'cod_cbr_ES/GP', 'cod_cbr_FE', 'cod_cbr_GH', 'cod_cbr_GN', 'cod_cbr_GN/ES', 'cod_cbr_GO', 'cod_cbr_GP/ES', 'hybride_oui', 'Carrosserie_BREAK', 'Carrosserie_CABRIOLET', 'Carrosserie_COMBISPACE', 'Carrosserie_COMBISPCACE', 'Carrosserie_COUPE', 'Carrosserie_MINIBUS', 'Carrosserie_MINISPACE', 'Carrosserie_MONOSPACE', 'Carrosserie_MONOSPACE COMPACT', 'Carrosserie_TS TERRAINS/CHEMINS', 'gamme_INFERIEURE', 'gamme_LUXE', 'gamme_MOY-INFER', 'gamme_MOY-INFERIEURE', 'gamme_MOY-SUPER', 'gamme_SUPERIEURE', 'typ_boite_nb_rapp_A 5', 'typ_boite_nb_rapp_A 6', 'typ_boite_nb_rapp_A 7', 'typ_boite_nb_rapp_A 8', 'typ_boite_nb_rapp_A 9', 'typ_boite_nb_rapp_D 5', 'typ_boite_nb_rapp_D 6', 'typ_boite_nb_rapp_D 7', 'typ_boite_nb_rapp_M 5', 'typ_boite_nb_rapp_M 6', 'typ_boite_nb_rapp_M 7', 'typ_boite_nb_rapp_S 6', 'typ_boite_nb_rapp_V .', 'typ_boite_nb_rapp_V 0']

In [20]:
from lazypredict import LazyRegressor
from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1)).fit(X_train)
X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

reg = LazyRegressor(verbose=0,ignore_warnings=False, custom_metric=None )
models,predictions = reg.fit(X_train_scaled, X_test_scaled, y_train, y_test)
print(models)

KernelRidge model failed to execute: Memory error in scipy.linalg.solve.
/Users/laura/Liora/Projet_CO2/.venv/lib/python3.12/site-packages/sklearn/svm/_base.py:1258: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  warnings.warn(
/Users/laura/Liora/Projet_CO2/.venv/lib/python3.12/site-packages/sklearn/neural_network/_multilayer_perceptron.py:785: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (200) reached and the optimization hasn't converged yet.
  warnings.warn(
/Users/laura/Liora/Projet_CO2/.venv/lib/python3.12/site-packages/sklearn/utils/deprecation.py:71: FutureWarning: Class PassiveAggressiveRegressor is deprecated; this is deprecated in version 1.8 and will be removed in 1.10. Use `SGDRegressor(loss='epsilon_insensitive', penalty=None, learning_rate='pa1', eta0 = 1.0)` instead.
  warnings.warn(msg, category=FutureWarning)

                                    Adjusted R-Squared                R-Squared             RMSE  Time Taken
Model
ExtraTreesRegressor                             0.9604                   0.9606           6.8266      1.9592
RandomForestRegressor                           0.9562                   0.9563           7.1865      2.8796
BaggingRegressor                                0.9551                   0.9553           7.2718      0.3090
ExtraTreeRegressor                              0.9547                   0.9548           7.3089      0.0404
DecisionTreeRegressor                           0.9521                   0.9523           7.5159      0.0635
HistGradientBoostingRegressor                   0.9455                   0.9457           8.0169      0.6453
MLPRegressor                                    0.9356                   0.9358           8.7135      7.1041
KNeighborsRegressor                             0.9269                   0.9272           9.2785      0.2305
GradientBoostingRegressor                       0.9237                   0.9240           9.4799      1.7034
AdaBoostRegressor                               0.8333                   0.8340          14.0133      0.8363
PoissonRegressor                                0.8319                   0.8326          14.0733      0.0683
LassoLarsCV                                     0.8256                   0.8263          14.3356      0.1167
Ridge                                           0.8256                   0.8263          14.3356      0.0251
RidgeCV                                         0.8256                   0.8263          14.3356      0.0625
LassoLarsIC                                     0.8256                   0.8263          14.3356      0.0728
LinearRegression                                0.8256                   0.8263          14.3356      0.0358
TransformedTargetRegressor                      0.8256                   0.8263          14.3356      0.0338
BayesianRidge                                   0.8256                   0.8263          14.3358      0.0440
LassoCV                                         0.8251                   0.8259          14.3535      0.1556
ElasticNetCV                                    0.8218                   0.8226          14.4892      0.1047
LarsCV                                          0.8212                   0.8219          14.5163      0.1245
Lasso                                           0.8044                   0.8052          15.1801      0.0370
LassoLars                                       0.8044                   0.8052          15.1803      0.0434
HuberRegressor                                  0.8028                   0.8036          15.2424      0.3984
LinearSVR                                       0.7988                   0.7997          15.3954      4.1614
OrthogonalMatchingPursuitCV                     0.7800                   0.7809          16.0984      0.0622
NuSVR                                           0.7779                   0.7788          16.1766     44.5777
SVR                                             0.7761                   0.7770          16.2427     48.3859
OrthogonalMatchingPursuit                       0.7432                   0.7443          17.3943      0.0239
ElasticNet                                      0.7373                   0.7383          17.5945      0.0249
TweedieRegressor                                0.6878                   0.6891          19.1797      0.0255
GammaRegressor                                  0.6871                   0.6884          19.1994      0.0248
RANSACRegressor                                 0.6264                   0.6279          20.9807      0.1260
PassiveAggressiveRegressor                      0.6203                   0.6218          21.1519      0.0471
DummyRegressor                                 -0.0041                  -0.0000          34.3963      0.0195
QuantileRegressor                              -0.0138                  -0.0096          34.5612     24.5326
GaussianProcessRegressor                     -478.5868                -476.6250         751.7145   1738.3247
Lars                                      -211650.8225             -210785.0529       15791.7532      0.1123
SGDRegressor                  -261731284985842176.0000 -260660663421951328.0000 17560915800.5428      0.0348

In [21]:
#afficher les resultats de Lazy Prdict en format numerique avec 4 decimales
import pandas as pd

models_display = models.copy()

# Arrondi des colonnes numériques
models_display = models_display.round(4)

# Affichage sans notation scientifique
pd.set_option(
    'display.float_format',
    lambda x: f'{x:.4f}'
)

display(models_display)

models_display.to_excel(
    "LazyPredict_resultats1.xlsx"
)

                                    Adjusted R-Squared                R-Squared             RMSE  Time Taken
Model
ExtraTreesRegressor                             0.9604                   0.9606           6.8266      1.9592
RandomForestRegressor                           0.9562                   0.9563           7.1865      2.8796
BaggingRegressor                                0.9551                   0.9553           7.2718      0.3090
ExtraTreeRegressor                              0.9547                   0.9548           7.3089      0.0404
DecisionTreeRegressor                           0.9521                   0.9523           7.5159      0.0635
HistGradientBoostingRegressor                   0.9455                   0.9457           8.0169      0.6453
MLPRegressor                                    0.9356                   0.9358           8.7135      7.1041
KNeighborsRegressor                             0.9269                   0.9272           9.2785      0.2305
GradientBoostingRegressor                       0.9237                   0.9240           9.4799      1.7034
AdaBoostRegressor                               0.8333                   0.8340          14.0133      0.8363
PoissonRegressor                                0.8319                   0.8326          14.0733      0.0683
LassoLarsCV                                     0.8256                   0.8263          14.3356      0.1167
Ridge                                           0.8256                   0.8263          14.3356      0.0251
RidgeCV                                         0.8256                   0.8263          14.3356      0.0625
LassoLarsIC                                     0.8256                   0.8263          14.3356      0.0728
LinearRegression                                0.8256                   0.8263          14.3356      0.0358
TransformedTargetRegressor                      0.8256                   0.8263          14.3356      0.0338
BayesianRidge                                   0.8256                   0.8263          14.3358      0.0440
LassoCV                                         0.8251                   0.8259          14.3535      0.1556
ElasticNetCV                                    0.8218                   0.8226          14.4892      0.1047
LarsCV                                          0.8212                   0.8219          14.5163      0.1245
Lasso                                           0.8044                   0.8052          15.1801      0.0370
LassoLars                                       0.8044                   0.8052          15.1803      0.0434
HuberRegressor                                  0.8028                   0.8036          15.2424      0.3984
LinearSVR                                       0.7988                   0.7997          15.3954      4.1614
OrthogonalMatchingPursuitCV                     0.7800                   0.7809          16.0984      0.0622
NuSVR                                           0.7779                   0.7788          16.1766     44.5777
SVR                                             0.7761                   0.7770          16.2427     48.3859
OrthogonalMatchingPursuit                       0.7432                   0.7443          17.3943      0.0239
ElasticNet                                      0.7373                   0.7383          17.5945      0.0249
TweedieRegressor                                0.6878                   0.6891          19.1797      0.0255
GammaRegressor                                  0.6871                   0.6884          19.1994      0.0248
RANSACRegressor                                 0.6264                   0.6279          20.9807      0.1260
PassiveAggressiveRegressor                      0.6203                   0.6218          21.1519      0.0471
DummyRegressor                                 -0.0041                  -0.0000          34.3963      0.0195
QuantileRegressor                              -0.0138                  -0.0096          34.5612     24.5326
GaussianProcessRegressor                     -478.5868                -476.6250         751.7145   1738.3247
Lars                                      -211650.8225             -210785.0529       15791.7532      0.1123
SGDRegressor                  -261731284985842176.0000 -260660663421951328.0000 17560915800.5428      0.0348

In [2]:
from sklearn.inspection import permutation_importance

result = permutation_importance(
    model,
    X_test,
    y_test,
    n_repeats=10,
    random_state=42
)

importance = pd.Series(
    result.importances_mean,
    index=X_test.columns
)

importance.sort_values(ascending=False)

NameError: name 'model' is not defined

In [6]:


# ==========================================
# Entrainer le model Ridge
# ==========================================

import pandas as pd

from sklearn.linear_model import Ridge
from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)
from sklearn.inspection import permutation_importance


# ==========================================
# Conversion de y en Series si nécessaire
# ==========================================

y_train = y_train.squeeze()
y_test = y_test.squeeze()


# ==========================================
# Création du modèle
# ==========================================

ridge = Ridge(
    alpha=1.0,
    random_state=42
)


# ==========================================
# Entraînement
# ==========================================

ridge.fit(X_train, y_train)


# ==========================================
# Prédictions
# ==========================================

y_pred = ridge.predict(X_test)


# ==========================================
# Evaluation
# ==========================================

mae = mean_absolute_error(y_test, y_pred)
rmse = mean_squared_error(y_test, y_pred) ** 0.5
r2 = r2_score(y_test, y_pred)

print("===== Performances du modèle Ridge =====")
print(f"MAE  : {mae:.2f}")
print(f"RMSE : {rmse:.2f}")
print(f"R²   : {r2:.4f}")


# ==========================================
# Coefficients du modèle
# ==========================================

coef = pd.DataFrame({
    "Variable": X_train.columns,
    "Coefficient": ridge.coef_
})

coef["Abs"] = coef["Coefficient"].abs()

coef = coef.sort_values(
    by="Abs",
    ascending=False
)

print("\n===== Variables les plus influentes (coefficients) =====")
print(coef[["Variable", "Coefficient"]])


# ==========================================
# Importance par permutation
# ==========================================

result = permutation_importance(
    ridge,
    X_test,
    y_test,
    n_repeats=10,
    random_state=42,
    scoring="r2"
)

importance = pd.DataFrame({
    "Variable": X_test.columns,
    "Importance": result.importances_mean
})

importance = importance.sort_values(
    by="Importance",
    ascending=False
)

print("\n===== Importance par permutation =====")
print(importance)

===== Performances du modèle Ridge =====
MAE  : 9.89
RMSE : 13.11
R²   : 0.8547

===== Variables les plus influentes (coefficients) =====
                 Variable  Coefficient
4    lib_mrq_ASTON MARTIN    83.789031
22    lib_mrq_LAMBORGHINI    82.147208
57            hybride_oui   -75.952969
37    lib_mrq_ROLLS-ROYCE    75.495124
63    Carrosserie_MINIBUS    69.585757
..                    ...          ...
16        lib_mrq_HYUNDAI    -1.641083
75  typ_boite_nb_rapp_A 6     1.422044
0               puiss_max     0.248987
3         masse_ordma_max     0.018497
2         masse_ordma_min     0.009534

[88 rows x 2 columns]

===== Importance par permutation =====
                 Variable  Importance
63    Carrosserie_MINIBUS    1.120133
0               puiss_max    0.234632
3         masse_ordma_max    0.099266
45     lib_mrq_VOLKSWAGEN    0.095092
83  typ_boite_nb_rapp_M 6    0.080361
..                    ...         ...
53             cod_cbr_GN   -0.000003
43         lib_mrq_SUZUKI   -0.000006
17       lib_mrq_INFINITI   -0.000014
51             cod_cbr_FE   -0.000022
15          lib_mrq_HONDA   -0.000075

[88 rows x 2 columns]

In [ ]:
# La pipeline complete pour entrainer les 4 modeles de regression et les comparer
# ======================================================
# Comparaison Linear Regression / Ridge / Lasso / Decision Tree
# ======================================================

import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import (
    LinearRegression,
    RidgeCV,
    LassoCV
)

from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)


# ======================================================
# Mise en forme de y
# ======================================================

y_train = y_train.squeeze()
y_test = y_test.squeeze()


# ======================================================
# Définition des modèles
# ======================================================

models = {

    "Linear Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LinearRegression())
    ]),

    "RidgeCV": Pipeline([
        ("scaler", StandardScaler()),
        ("model", RidgeCV(
            alphas=[0.001, 0.01, 0.1, 1, 10, 50, 100]
        ))
    ]),

    "LassoCV": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LassoCV(
            alphas=[0.001, 0.01, 0.1, 1, 10],
            max_iter=5000,
            random_state=42
        ))
    ]),

    "Decision Tree": Pipeline([
        ("model", DecisionTreeRegressor(
            random_state=42
        ))
    ])
}


# ======================================================
# Entraînement + Evaluation
# ======================================================

results = []

trained_models = {}


for name, model in models.items():

    print(f"Entraînement : {name}")

    # entraînement
    model.fit(
        X_train,
        y_train
    )

    # sauvegarde du modèle entraîné
    trained_models[name] = model

    # prédictions
    y_pred = model.predict(
        X_test
    )

    # métriques
    mae = mean_absolute_error(
        y_test,
        y_pred
    )

    rmse = mean_squared_error(
        y_test,
        y_pred
    ) ** 0.5

    r2 = r2_score(
        y_test,
        y_pred
    )

    results.append({
        "Modèle": name,
        "MAE": round(mae, 3),
        "RMSE": round(rmse, 3),
        "R²": round(r2, 4)
    })


# ======================================================
# Tableau final
# ======================================================

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="R²",
    ascending=False
)


print("\n===== Comparaison des modèles =====")
display(results_df)


# ======================================================
# Afficher le meilleur modèle
# ======================================================

best_model_name = results_df.iloc[0]["Modèle"]

print("\nMeilleur modèle :")
print(best_model_name)


best_model = trained_models[best_model_name]