In [25]:
# Charger le dataset sauvegardé
import pandas as pd
X_test = pd.read_csv("../data/X_test_final.csv")
X_train = pd.read_csv("../data/X_train_final.csv")
y_test = pd.read_csv("../data/y_test.csv")
y_train = pd.read_csv("../data/y_train.csv")
X_test.head()

,puiss_max,conso_mixte,co_typ_1,nox,ptcl,masse_ordma_min,masse_ordma_max,lib_mrq_ASTON MARTIN,lib_mrq_AUDI,lib_mrq_BENTLEY,...,typ_boite_nb_rapp_A 9,typ_boite_nb_rapp_D 5,typ_boite_nb_rapp_D 6,typ_boite_nb_rapp_D 7,typ_boite_nb_rapp_M 5,typ_boite_nb_rapp_M 6,typ_boite_nb_rapp_M 7,typ_boite_nb_rapp_S 6,typ_boite_nb_rapp_V .,typ_boite_nb_rapp_V 0
0,100.0000,8.0000,0.0780,0.2240,0.0010,2025,2075,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
1,120.0000,8.1000,0.0870,0.2750,0.0000,2076,2185,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000,0.0000
2,120.0000,7.3000,0.0460,0.1970,0.0000,2186,2355,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000
3,120.0000,7.7000,0.1750,0.2260,0.0010,2186,2350,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000
4,80.0000,8.0000,0.1370,0.2140,0.0010,1976,2783,0.0000,0.0000,0.0000,...,0.0000,0.0000,0.0000,0.0000,0.0000,1.0000,0.0000,0.0000,0.0000,0.0000

In [9]:
#afficher dataset chargé

print(y_train.shape)
print(y_test.shape)

(44008, 1)
(11002, 1)

In [26]:
# transformer les datasets y_train et y_test en vecteurs 1D

y_train = y_train.squeeze()
y_test = y_test.squeeze()

print(type(X_train))
print(type(X_test)) 
print(type(y_train))
print(type(y_test))
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

<class 'pandas.DataFrame'>
<class 'pandas.DataFrame'>
<class 'pandas.Series'>
<class 'pandas.Series'>
(44008, 91)
(44008,)
(11002, 91)
(11002,)

In [27]:
# 1 er cas de figure : 4 Colonnes à supprimer du dataset 
cols_a_supprimer = [
    "co_typ_1",
    "conso_mixte",
    "nox",
    "ptcl"
]

X_train = X_train.drop(columns=cols_a_supprimer)
X_test = X_test.drop(columns=cols_a_supprimer)

print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

print(X_train.columns.tolist())

(44008, 87)
(44008,)
(11002, 87)
(11002,)
['puiss_max', 'masse_ordma_min', 'masse_ordma_max', 'lib_mrq_ASTON MARTIN', 'lib_mrq_AUDI', 'lib_mrq_BENTLEY', 'lib_mrq_BMW', 'lib_mrq_CADILLAC', 'lib_mrq_CHEVROLET', 'lib_mrq_CITROEN', 'lib_mrq_DACIA', 'lib_mrq_FERRARI', 'lib_mrq_FIAT', 'lib_mrq_FORD', 'lib_mrq_HONDA', 'lib_mrq_HYUNDAI', 'lib_mrq_INFINITI', 'lib_mrq_JAGUAR', 'lib_mrq_JEEP', 'lib_mrq_KIA', 'lib_mrq_LADA', 'lib_mrq_LAMBORGHINI', 'lib_mrq_LANCIA', 'lib_mrq_LAND ROVER', 'lib_mrq_LEXUS', 'lib_mrq_LOTUS', 'lib_mrq_MASERATI', 'lib_mrq_MAZDA', 'lib_mrq_MERCEDES', 'lib_mrq_MINI', 'lib_mrq_MITSUBISHI', 'lib_mrq_NISSAN', 'lib_mrq_OPEL', 'lib_mrq_PEUGEOT', 'lib_mrq_PORSCHE', 'lib_mrq_RENAULT', 'lib_mrq_ROLLS-ROYCE', 'lib_mrq_SEAT', 'lib_mrq_SKODA', 'lib_mrq_SMART', 'lib_mrq_SSANGYONG', 'lib_mrq_SUBARU', 'lib_mrq_SUZUKI', 'lib_mrq_TOYOTA', 'lib_mrq_VOLKSWAGEN', 'lib_mrq_VOLVO', 'cod_cbr_EH', 'cod_cbr_ES', 'cod_cbr_ES/GN', 'cod_cbr_ES/GP', 'cod_cbr_FE', 'cod_cbr_GH', 'cod_cbr_GN', 'cod_cbr_GN/ES', 'cod_cbr_GO', 'cod_cbr_GP/ES', 'hybride_oui', 'Carrosserie_BREAK', 'Carrosserie_CABRIOLET', 'Carrosserie_COMBISPACE', 'Carrosserie_COMBISPCACE', 'Carrosserie_COUPE', 'Carrosserie_MINIBUS', 'Carrosserie_MINISPACE', 'Carrosserie_MONOSPACE', 'Carrosserie_MONOSPACE COMPACT', 'Carrosserie_TS TERRAINS/CHEMINS', 'gamme_INFERIEURE', 'gamme_LUXE', 'gamme_MOY-INFER', 'gamme_MOY-INFERIEURE', 'gamme_MOY-SUPER', 'gamme_SUPERIEURE', 'typ_boite_nb_rapp_A 5', 'typ_boite_nb_rapp_A 6', 'typ_boite_nb_rapp_A 7', 'typ_boite_nb_rapp_A 8', 'typ_boite_nb_rapp_A 9', 'typ_boite_nb_rapp_D 5', 'typ_boite_nb_rapp_D 6', 'typ_boite_nb_rapp_D 7', 'typ_boite_nb_rapp_M 5', 'typ_boite_nb_rapp_M 6', 'typ_boite_nb_rapp_M 7', 'typ_boite_nb_rapp_S 6', 'typ_boite_nb_rapp_V .', 'typ_boite_nb_rapp_V 0']

In [19]:
# 2 eme cas de figure : 4 Colonnes à supprimer du 1er cas. + toutes les libellés des marques de voitures (ex: "marque_1", "marque_2", "marque_3", etc.)

cols_a_supprimer = [
    "co_typ_1",
    "conso_mixte",
    "nox",
    "ptcl"
]

X_train = X_train.drop(columns=cols_a_supprimer)
X_test = X_test.drop(columns=cols_a_supprimer)

#supprimer des marques:
cols_lib_mrq = X_train.filter(regex="^lib_mrq_").columns

X_train.drop(columns=cols_lib_mrq, inplace=True)
X_test.drop(columns=cols_lib_mrq, inplace=True)

print(X_train.columns.tolist())

['puiss_max', 'masse_ordma_min', 'masse_ordma_max', 'cod_cbr_EH', 'cod_cbr_ES', 'cod_cbr_ES/GN', 'cod_cbr_ES/GP', 'cod_cbr_FE', 'cod_cbr_GH', 'cod_cbr_GN', 'cod_cbr_GN/ES', 'cod_cbr_GO', 'cod_cbr_GP/ES', 'hybride_oui', 'Carrosserie_BREAK', 'Carrosserie_CABRIOLET', 'Carrosserie_COMBISPACE', 'Carrosserie_COMBISPCACE', 'Carrosserie_COUPE', 'Carrosserie_MINIBUS', 'Carrosserie_MINISPACE', 'Carrosserie_MONOSPACE', 'Carrosserie_MONOSPACE COMPACT', 'Carrosserie_TS TERRAINS/CHEMINS', 'gamme_INFERIEURE', 'gamme_LUXE', 'gamme_MOY-INFER', 'gamme_MOY-INFERIEURE', 'gamme_MOY-SUPER', 'gamme_SUPERIEURE', 'typ_boite_nb_rapp_A 5', 'typ_boite_nb_rapp_A 6', 'typ_boite_nb_rapp_A 7', 'typ_boite_nb_rapp_A 8', 'typ_boite_nb_rapp_A 9', 'typ_boite_nb_rapp_D 5', 'typ_boite_nb_rapp_D 6', 'typ_boite_nb_rapp_D 7', 'typ_boite_nb_rapp_M 5', 'typ_boite_nb_rapp_M 6', 'typ_boite_nb_rapp_M 7', 'typ_boite_nb_rapp_S 6', 'typ_boite_nb_rapp_V .', 'typ_boite_nb_rapp_V 0']

In [ ]:
#from lazypredict import LazyRegressor
#from sklearn.preprocessing import MinMaxScaler
#scaler = MinMaxScaler(feature_range=(0, 1)).fit(X_train)
#X_train_scaled = scaler.transform(X_train)
#X_test_scaled = scaler.transform(X_test)

#reg = LazyRegressor(verbose=0,ignore_warnings=False, custom_metric=None )
#models,predictions = reg.fit(X_train_scaled, X_test_scaled, y_train, y_test)
#print(models)

In [ ]:
#afficher les resultats de Lazy Prdict en format numerique avec 4 decimales
import pandas as pd

models_display = models.copy()

# Arrondi des colonnes numériques
models_display = models_display.round(4)

# Affichage sans notation scientifique
pd.set_option(
    'display.float_format',
    lambda x: f'{x:.4f}'
)

display(models_display)

models_display.to_excel(
    "LazyPredict_resultats2.xlsx"
)

In [ ]:
from sklearn.inspection import permutation_importance

result = permutation_importance(
    model,
    X_test,
    y_test,
    n_repeats=10,
    random_state=42
)

importance = pd.Series(
    result.importances_mean,
    index=X_test.columns
)

importance.sort_values(ascending=False)

In [ ]:
# La pipeline complete pour entrainer les 4 modeles de regression et les comparer
# ======================================================
# Comparaison Linear Regression / Ridge / Lasso / Decision Tree
# ======================================================

import pandas as pd

from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import (
    LinearRegression,
    RidgeCV,
    LassoCV
)

from sklearn.tree import DecisionTreeRegressor

from sklearn.metrics import (
    mean_absolute_error,
    mean_squared_error,
    r2_score
)


# ======================================================
# Mise en forme de y
# ======================================================

y_train = y_train.squeeze()
y_test = y_test.squeeze()


# ======================================================
# Définition des modèles
# ======================================================

models = {

    "Linear Regression": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LinearRegression())
    ]),

    "RidgeCV": Pipeline([
        ("scaler", StandardScaler()),
        ("model", RidgeCV(
            alphas=[0.001, 0.01, 0.1, 1, 10, 50, 100]
        ))
    ]),

    "LassoCV": Pipeline([
        ("scaler", StandardScaler()),
        ("model", LassoCV(
            alphas=[0.001, 0.01, 0.1, 1, 10],
            max_iter=5000,
            random_state=42
        ))
    ]),

    "Decision Tree": Pipeline([
        ("model", DecisionTreeRegressor(
            random_state=42
        ))
    ])
}


# ======================================================
# Entraînement + Evaluation
# ======================================================

results = []

trained_models = {}


for name, model in models.items():

    print(f"Entraînement : {name}")

    # entraînement
    model.fit(
        X_train,
        y_train
    )

    # sauvegarde du modèle entraîné
    trained_models[name] = model

    # prédictions
    y_pred = model.predict(
        X_test
    )

    # métriques
    mae = mean_absolute_error(
        y_test,
        y_pred
    )

    rmse = mean_squared_error(
        y_test,
        y_pred
    ) ** 0.5

    r2 = r2_score(
        y_test,
        y_pred
    )

    results.append({
        "Modèle": name,
        "MAE": round(mae, 3),
        "RMSE": round(rmse, 3),
        "R²": round(r2, 4)
    })


# ======================================================
# Tableau final
# ======================================================

results_df = pd.DataFrame(results)

results_df = results_df.sort_values(
    by="R²",
    ascending=False
)


print("\n===== Comparaison des modèles =====")
display(results_df)


# ======================================================
# Afficher le meilleur modèle
# ======================================================

best_model_name = results_df.iloc[0]["Modèle"]

print("\nMeilleur modèle :")
print(best_model_name)


best_model = trained_models[best_model_name]

In [ ]:
# =============================================================================
# COMPARAISON DE MODELES DE REGRESSION AVEC VALIDATION CROISEE
#
# Modèles :
# - Régression linéaire
# - RidgeCV
# - LassoCV
# - Arbre de décision optimisé par GridSearchCV
#
# Métriques :
# - R²
# - RMSE
# - MAE
# - MAPE
# =============================================================================


import pandas as pd

from sklearn.model_selection import (
    KFold,
    cross_validate,
    GridSearchCV
)

from sklearn.linear_model import (
    LinearRegression,
    RidgeCV,
    LassoCV
)

from sklearn.tree import DecisionTreeRegressor



# =============================================================================
# 1) VALIDATION CROISEE
# =============================================================================

cv = KFold(
    n_splits=5,
    shuffle=True,
    random_state=42
)



# =============================================================================
# 2) RECHERCHE DU MEILLEUR RIDGE
#
# Ridge ajoute une pénalité L2 :
# elle réduit l'impact des coefficients trop élevés
#
# RidgeCV teste plusieurs valeurs de alpha
# =============================================================================

alphas_ridge = [
    0.001,
    0.01,
    0.1,
    0.3,
    0.7,
    1,
    10,
    50,
    100
]


ridge = RidgeCV(
    alphas=alphas_ridge,
    cv=cv,
    scoring="r2"
)

ridge.fit(
    X_train,
    y_train
)


print(
    "Meilleur alpha Ridge :",
    ridge.alpha_
)



# =============================================================================
# 3) RECHERCHE DU MEILLEUR LASSO
#
# Lasso réalise une sélection automatique de variables
# grâce à une pénalité L1
# =============================================================================


alphas_lasso = [
    0.001,
    0.01,
    0.1,
    0.3,
    0.7,
    1,
    10
]


lasso = LassoCV(
    alphas=alphas_lasso,
    cv=cv,
    max_iter=10000,
    random_state=42
)


lasso.fit(
    X_train,
    y_train
)


print(
    "Meilleur alpha Lasso :",
    lasso.alpha_
)



# =============================================================================
# 4) RECHERCHE DU MEILLEUR ARBRE DE DECISION
#
# Paramètres optimisés :
# - profondeur maximale
# - nombre minimum d'observations pour couper un noeud
# - nombre minimum d'observations dans une feuille
# =============================================================================


tree = DecisionTreeRegressor(
    random_state=42
)


param_grid_tree = {

    "max_depth":[
        5,
        10,
        15,
        20,
        None
    ],

    "min_samples_split":[
        2,
        5,
        10,
        20
    ],

    "min_samples_leaf":[
        1,
        2,
        5,
        10
    ]

}



tree_grid = GridSearchCV(

    estimator=tree,

    param_grid=param_grid_tree,

    scoring="r2",

    cv=cv,

    n_jobs=-1

)


tree_grid.fit(
    X_train,
    y_train
)



best_tree = tree_grid.best_estimator_


print(
    "Meilleurs paramètres arbre :",
    tree_grid.best_params_
)



# =============================================================================
# 5) MODELES FINAUX A COMPARER
# =============================================================================


models = {

    "Régression linéaire":
        LinearRegression(),

    "Ridge optimisé":
        ridge,

    "Lasso optimisé":
        lasso,

    "Arbre décision optimisé":
        best_tree

}



# =============================================================================
# 6) VALIDATION CROISEE DES MODELES OPTIMISES
# =============================================================================


results = []


for name, model in models.items():

    scores = cross_validate(

        model,

        X_train,

        y_train,

        cv=cv,

        scoring={

            "R2":
                "r2",

            "RMSE":
                "neg_root_mean_squared_error",

            "MAE":
                "neg_mean_absolute_error",

            "MAPE":
                "neg_mean_absolute_percentage_error"

        },

        n_jobs=-1

    )


    results.append({

        "Modèle": name,


        "R² moyen":
            scores["test_R2"].mean(),


        "R² écart-type":
            scores["test_R2"].std(),


        "RMSE moyen":
            -scores["test_RMSE"].mean(),


        "MAE moyen":
            -scores["test_MAE"].mean(),


        "MAPE moyen (%)":
            -scores["test_MAPE"].mean()*100

    })



# =============================================================================
# 7) TABLEAU FINAL
# =============================================================================


results_df = pd.DataFrame(results)


results_df = results_df.sort_values(
    by="R² moyen",
    ascending=False
)


results_df = results_df.round(4)



display(results_df)



# =============================================================================
# 8) EXPORT EXCEL
# =============================================================================


results_df.to_excel(
    "Comparaison_modeles_validation_croisee1.xlsx",
    index=False
)


print(
    "Export terminé : Comparaison_modeles_validation_croisee1.xlsx"
)

Meilleur alpha Ridge : 0.1
Meilleur alpha Lasso : 0.001
Meilleurs paramètres arbre : {'max_depth': None, 'min_samples_leaf': 1, 'min_samples_split': 2}

,Modèle,R² moyen,R² écart-type,RMSE moyen,MAE moyen,MAPE moyen (%)
3,Arbre décision optimisé,0.9505,0.0019,7.5351,5.4434,2.8281
0,Régression linéaire,0.8546,0.0058,12.9100,9.8871,5.0807
1,Ridge optimisé,0.8546,0.0057,12.9121,9.8894,5.0803
2,Lasso optimisé,0.8543,0.0054,12.9236,9.9009,5.0833

Export terminé : Comparaison_modeles_validation_croisee.xlsx