## Pré-processing et Feature Engineering

## Chargement des données

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [2]:
df_2014 = pd.read_csv(
    "../data/co2_2014.csv",
    encoding="latin1",
    sep=";"
)

df_2014.head()

,lib_mrq,lib_mod_doss,lib_mod,dscom,cnit,tvv,cod_cbr,hybride,puiss_admin_98,puiss_max,typ_boite_nb_rapp,conso_urb,conso_exurb,conso_mixte,co2,co_typ_1,hc,nox,hcnox,ptcl,masse_ordma_min,masse_ordma_max,champ_v9,date_maj,Carrosserie,gamme,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,ALFA-ROMEO,159,159,159 1750 Tbi (200ch),M10ALFVP000G340,939AXN1B52C,ES,non,12,147,M 6,"11,30000019","5,800000191","7,800000191",182.0,"0,647000015","0,052000001","0,032000002",NaN,"0,002",1505,1505,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
1,ALFA-ROMEO,159,159,159 1750 Tbi (200ch),M10ALFVP000H341,939BXN1B53C,ES,non,12,147,M 6,"11,5",6,8,186.0,"0,647000015","0,052000001","0,032000002",NaN,"0,002",1555,1555,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
2,ALFA-ROMEO,159,159,159 2.0 JTDm (136ch),M10ALFVP000E302,939AXR1B64,GO,non,7,100,M 6,"6,599999905","4,199999809","5,099999905",134.0,"0,066",NaN,"0,149000004","0,174999997","0,001",1565,1565,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
3,ALFA-ROMEO,159,159,159 2.0 JTDm (136ch),M10ALFVP000F303,939AXR1B64B,GO,non,7,100,M 6,"6,599999905","4,199999809","5,099999905",134.0,"0,066",NaN,"0,149000004","0,174999997","0,001",1565,1565,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
4,ALFA-ROMEO,159,159,159 2.0 JTDm (170ch),M10ALFVP000G304,939AXS1B66,GO,non,9,125,M 6,"6,900000095","4,300000191","5,300000191",139.0,"0,059999999",NaN,"0,164000005","0,193000004","0,001",1565,1565,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN


## État initial du dataset

In [3]:

df_2014.shape

(55044, 30)

In [4]:
df_2014.info()

<class 'pandas.DataFrame'>
RangeIndex: 55044 entries, 0 to 55043
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lib_mrq            55044 non-null  str
 1   lib_mod_doss       55044 non-null  str
 2   lib_mod            55044 non-null  str
 3   dscom              55044 non-null  str
 4   cnit               55044 non-null  str
 5   tvv                55044 non-null  str
 6   cod_cbr            55044 non-null  str
 7   hybride            55044 non-null  str
 8   puiss_admin_98     55044 non-null  int64
 9   puiss_max          55044 non-null  str
 10  typ_boite_nb_rapp  55044 non-null  str
 11  conso_urb          55001 non-null  str
 12  conso_exurb        55001 non-null  str
 13  conso_mixte        55010 non-null  str
 14  co2                55010 non-null  float64
 15  co_typ_1           54886 non-null  str
 16  hc                 9773 non-null   str
 17  nox                54886 non-null  str
 18  hcnox              45156 non-null  str
 19  ptcl               52366 non-null  str
 20  masse_ordma_min    55044 non-null  int64
 21  masse_ordma_max    55044 non-null  int64
 22  champ_v9           54983 non-null  str
 23  date_maj           3247 non-null   str
 24  Carrosserie        55044 non-null  str
 25  gamme              55044 non-null  str
 26  Unnamed: 26        0 non-null      float64
 27  Unnamed: 27        0 non-null      float64
 28  Unnamed: 28        0 non-null      float64
 29  Unnamed: 29        0 non-null      float64
dtypes: float64(5), int64(3), str(22)
memory usage: 12.6 MB

Le jeu de données contient 55 044 observations et 30 variables.

Les variables décrivent les caractéristiques techniques des véhicules homologués en France en 2014 : marque, modèle, type de carburant, puissance, consommation, masse, norme environnementale et émissions de CO₂.

Avant toute modélisation, une phase de pré-processing est nécessaire afin de traiter les valeurs manquantes, convertir les types de données et préparer le dataset pour les futures analyses.

## Analyse des valeurs manquantes

In [5]:
(df_2014.isnull().mean() * 100).sort_values(ascending=False)

Unnamed: 27          100.000000
Unnamed: 26          100.000000
Unnamed: 29          100.000000
Unnamed: 28          100.000000
date_maj              94.101083
hc                    82.245113
hcnox                 17.963811
ptcl                   4.865199
nox                    0.287043
co_typ_1               0.287043
champ_v9               0.110820
conso_urb              0.078119
conso_exurb            0.078119
conso_mixte            0.061769
co2                    0.061769
typ_boite_nb_rapp      0.000000
puiss_admin_98         0.000000
hybride                0.000000
cod_cbr                0.000000
dscom                  0.000000
cnit                   0.000000
tvv                    0.000000
lib_mod_doss           0.000000
lib_mrq                0.000000
lib_mod                0.000000
puiss_max              0.000000
masse_ordma_max        0.000000
masse_ordma_min        0.000000
gamme                  0.000000
Carrosserie            0.000000
dtype: float64

L'analyse des valeurs manquantes met en évidence plusieurs variables fortement incomplètes.

Les colonnes `Unnamed: 26` à `Unnamed: 29` sont entièrement vides, tandis que la variable `date_maj` présente plus de 94 % de valeurs manquantes. Parmi les variables environnementales, `hc` affiche plus de 82 % de données manquantes et `hcnox` près de 18 %.

À l'inverse, la majorité des autres variables sont quasiment complètes, avec moins de 1 % de valeurs manquantes.

Ces résultats orientent les choix de pré-processing à mettre en œuvre, notamment la suppression des variables les moins exploitables et le traitement ciblé des valeurs manquantes restantes.

## Suppression des colonnes vides et peu exploitables

In [6]:
colonnes_a_supprimer = [
    'Unnamed: 26',
    'Unnamed: 27',
    'Unnamed: 28',
    'Unnamed: 29',
    'date_maj'
]

df_2014 = df_2014.drop(columns=colonnes_a_supprimer)

df_2014.shape

(55044, 25)


Les colonnes `Unnamed: 26` à `Unnamed: 29` ont été supprimées car elles étaient entièrement vides et n'apportaient aucune information exploitable.

La variable `date_maj` a également été retirée du jeu de données. Avec plus de 94 % de valeurs manquantes et sans lien direct avec les caractéristiques techniques des véhicules ou les émissions de CO₂, son exploitation apparaissait peu pertinente pour la suite du projet.

Le dataset passe ainsi de 30 à 25 variables tout en conservant les 55 044 observations initiales.

## Traitement des variables fortement incomplètes

In [7]:
df_2014 = df_2014.drop(columns=['hc', 'hcnox'])

df_2014.shape

(55044, 23)

Les variables `hc` et `hcnox` présentent respectivement plus de 82 % et près de 18 % de valeurs manquantes.

Compte tenu de leur faible niveau de complétude, elles ont été supprimées du jeu de données afin de limiter les traitements d'imputation et de conserver un dataset plus robuste pour la modélisation.

La variable `ptcl`, bien qu'incomplète, a été conservée car son taux de valeurs manquantes reste limité (moins de 5 %) et son contenu demeure potentiellement pertinent pour l'analyse des émissions polluantes.

Le dataset passe ainsi de 25 à 23 variables.

## Conversion des variables numériques

In [8]:
colonnes_numeriques = [
    'puiss_max',
    'conso_urb',
    'conso_exurb',
    'conso_mixte',
    'co_typ_1',
    'nox',
    'ptcl'
]

for col in colonnes_numeriques:
    df_2014[col] = (
        df_2014[col]
        .str.replace(',', '.', regex=False)
    )

    df_2014[col] = pd.to_numeric(df_2014[col], errors='coerce')

In [9]:
df_2014.info()

<class 'pandas.DataFrame'>
RangeIndex: 55044 entries, 0 to 55043
Data columns (total 23 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lib_mrq            55044 non-null  str
 1   lib_mod_doss       55044 non-null  str
 2   lib_mod            55044 non-null  str
 3   dscom              55044 non-null  str
 4   cnit               55044 non-null  str
 5   tvv                55044 non-null  str
 6   cod_cbr            55044 non-null  str
 7   hybride            55044 non-null  str
 8   puiss_admin_98     55044 non-null  int64
 9   puiss_max          55044 non-null  float64
 10  typ_boite_nb_rapp  55044 non-null  str
 11  conso_urb          55001 non-null  float64
 12  conso_exurb        55001 non-null  float64
 13  conso_mixte        55010 non-null  float64
 14  co2                55010 non-null  float64
 15  co_typ_1           54886 non-null  float64
 16  nox                54886 non-null  float64
 17  ptcl               52366 non-null  float64
 18  masse_ordma_min    55044 non-null  int64
 19  masse_ordma_max    55044 non-null  int64
 20  champ_v9           54983 non-null  str
 21  Carrosserie        55044 non-null  str
 22  gamme              55044 non-null  str
dtypes: float64(8), int64(3), str(12)
memory usage: 9.7 MB

Certaines variables quantitatives étaient initialement stockées sous forme de chaînes de caractères en raison de l'utilisation de la virgule comme séparateur décimal.

Ces variables ont été converties au format numérique (`float64`) afin de permettre les calculs statistiques et les traitements de pré-processing.

Cette conversion a également permis d'identifier les valeurs invalides, désormais représentées sous forme de valeurs manquantes (`NaN`) qui seront traitées dans les étapes suivantes.

## Choix de la méthode d'imputation

Les variables ptcl, nox et co_typ_1 présentent un faible taux de valeurs manquantes (inférieur à 5 %). Plusieurs stratégies d'imputation pouvaient être envisagées afin de conserver l'ensemble des observations du jeu de données.

Une première approche consistait à réaliser une imputation par marque de véhicule. Cette solution n'a toutefois pas été retenue car la répartition des marques est fortement déséquilibrée. Certaines marques sont représentées par plusieurs dizaines de milliers d'observations tandis que d'autres ne comptent que quelques dizaines de véhicules. Les médianes calculées pour les marques les moins représentées auraient donc été peu robustes.

Une seconde approche reposait sur une imputation par type de carburant. Cette stratégie apparaît particulièrement pertinente pour certaines variables environnementales, les émissions polluantes étant directement liées à la motorisation des véhicules. Une analyse des médianes par carburant a donc été réalisée afin d'évaluer cette hypothèse.

Enfin, une troisième approche consistait à utiliser la médiane globale du jeu de données. Cette méthode simple et robuste permet de limiter l'influence des valeurs extrêmes tout en conservant l'ensemble des observations.

Les analyses réalisées ont montré que les variables nox et co_typ_1 présentent des différences importantes selon le carburant, notamment entre les motorisations essence et diesel. En conséquence, une imputation conditionnelle par carburant a été retenue pour ces deux variables. En revanche, les médianes de ptcl étant très proches entre les différentes catégories de carburant, une imputation par la médiane globale a été conservée.

In [17]:
# Répartition des carburants
df_2014['cod_cbr'].value_counts()

cod_cbr
GO       49311
ES        5166
EH         298
GH          81
ES/GP       23
GP/ES       23
GN          21
ES/GN       20
GN/ES       20
FE          10
GL           1
Name: count, dtype: int64

In [18]:
# Médianes NOx par carburant
df_2014.groupby('cod_cbr')['nox'].median().sort_values()

cod_cbr
EH       0.006
ES/GP    0.018
FE       0.020
GP/ES    0.026
ES       0.030
GN/ES    0.031
GN       0.032
ES/GN    0.036
GL       0.036
GH       0.061
GO       0.214
Name: nox, dtype: float64

In [19]:
# Médianes PTCL par carburant
df_2014.groupby('cod_cbr')['ptcl'].median().sort_values()

cod_cbr
GL       0.000
EH       0.001
ES/GN    0.001
ES       0.001
ES/GP    0.001
FE       0.001
GH       0.001
GN       0.001
GN/ES    0.001
GO       0.001
GP/ES    0.001
Name: ptcl, dtype: float64

In [20]:
# Médianes CO par carburant
df_2014.groupby('cod_cbr')['co_typ_1'].median().sort_values()

cod_cbr
GL       0.0200
GO       0.1000
EH       0.1870
GH       0.2220
ES       0.2345
GN/ES    0.2580
ES/GN    0.3050
GP/ES    0.3590
ES/GP    0.3600
GN       0.3700
FE       0.6320
Name: co_typ_1, dtype: float64

In [21]:
df_2014.groupby('cod_cbr')[['nox', 'co_typ_1']].count()

           nox  co_typ_1
cod_cbr
EH         298       298
ES        5166      5166
ES/GN       20        20
ES/GP       23        23
FE          10        10
GH          81        81
GL           1         1
GN          21        21
GN/ES       20        20
GO       49311     49311
GP/ES       23        23

## Analyse des résultats

L'analyse des médianes par carburant met en évidence des différences importantes pour les variables nox et co_typ_1, notamment entre les véhicules diesel (GO) et essence (ES).

Pour la variable nox, la médiane observée pour les véhicules diesel (0,214) est significativement supérieure à celle des véhicules essence (0,030). Une différence notable est également observée pour co_typ_1, avec des médianes respectives de 0,100 pour le diesel et 0,235 pour l'essence.

À l'inverse, les médianes de ptcl sont quasiment identiques quel que soit le carburant considéré, ce qui suggère une faible influence de cette variable de regroupement.

Les effectifs observés pour les principales catégories de carburant sont suffisamment importants pour garantir la robustesse des médianes calculées.

Ces résultats justifient le recours à une imputation conditionnelle par carburant pour les variables nox et co_typ_1, tandis qu'une imputation par la médiane globale est conservée pour ptcl.

In [22]:
df_2014['ptcl'] = df_2014['ptcl'].fillna(df_2014['ptcl'].median())

df_2014['nox'] = (
    df_2014.groupby('cod_cbr')['nox']
           .transform(lambda x: x.fillna(x.median()))
)

df_2014['co_typ_1'] = (
    df_2014.groupby('cod_cbr')['co_typ_1']
           .transform(lambda x: x.fillna(x.median()))
)

In [23]:
df_2014[['ptcl', 'nox', 'co_typ_1']].isnull().sum()

ptcl        0
nox         0
co_typ_1    0
dtype: int64

Les valeurs manquantes des variables environnementales ont été imputées selon la méthode retenue. Aucune valeur manquante ne subsiste désormais pour les variables ptcl, nox et co_typ_1.

## Traitement des valeurs manquantes restantes

In [24]:
df_2014.isnull().sum().sort_values(ascending=False).head(10)

lib_mrq           0
lib_mod_doss      0
lib_mod           0
dscom             0
cnit              0
tvv               0
cod_cbr           0
hybride           0
puiss_admin_98    0
puiss_max         0
dtype: int64

Après l'imputation des variables environnementales, seules quelques valeurs manquantes subsistent dans le dataset.

La variable cible `co2` présente encore 34 valeurs manquantes. Ces observations seront supprimées afin de garantir la qualité de la future modélisation.

Les variables `conso_urb`, `conso_exurb` et `conso_mixte` présentent un nombre très limité de valeurs manquantes, qui seront traitées dans les étapes suivantes.

## Supprimer les lignes où le CO₂ est manquant

In [13]:
df_2014 = df_2014.dropna(subset=['co2'])

In [14]:
df_2014.isnull().sum().sort_values(ascending=False).head(10)

champ_v9        27
conso_exurb      9
conso_urb        9
dscom            0
lib_mrq          0
lib_mod_doss     0
lib_mod          0
cod_cbr          0
tvv              0
cnit             0
dtype: int64

In [15]:
df_2014 = df_2014.dropna()

df_2014.isnull().sum().sum()

np.int64(0)

### Finalisation du traitement des valeurs manquantes

Après la suppression des observations dont la variable cible (co2) était manquante, seules quelques valeurs manquantes subsistaient dans le dataset, principalement sur la variable champ_v9.

Compte tenu du très faible nombre d'observations concernées (moins de 0,05 % du dataset), ces lignes ont été supprimées.

Le jeu de données final ne contient ainsi plus aucune valeur manquante et est désormais prêt pour les étapes de transformation et de modélisation.

## État final du dataset après pré-processing

In [16]:
df_2014.shape

(54974, 23)

Le dataset final contient 54 974 observations et 23 variables après les différentes étapes de pré-processing.

Les colonnes vides ou fortement incomplètes (`Unnamed`, `date_maj`, `hc` et `hcnox`) ont été supprimées. Les variables numériques stockées sous forme de texte ont été converties au format approprié et les valeurs manquantes ont été traitées par suppression ou imputation lorsque cela était nécessaire.

Le jeu de données est désormais propre, cohérent et prêt pour les étapes de transformation des variables et de modélisation des émissions de CO₂.