## Pré-processing et Feature Engineering

## Chargement des données

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", None)

In [20]:
df_2014 = pd.read_csv(
    "../data/co2_2014.csv",
    encoding="latin1",
    sep=";"
)

df_2014.head()

,lib_mrq,lib_mod_doss,lib_mod,dscom,cnit,tvv,cod_cbr,hybride,puiss_admin_98,puiss_max,typ_boite_nb_rapp,conso_urb,conso_exurb,conso_mixte,co2,co_typ_1,hc,nox,hcnox,ptcl,masse_ordma_min,masse_ordma_max,champ_v9,date_maj,Carrosserie,gamme,Unnamed: 26,Unnamed: 27,Unnamed: 28,Unnamed: 29
0,ALFA-ROMEO,159,159,159 1750 Tbi (200ch),M10ALFVP000G340,939AXN1B52C,ES,non,12,147,M 6,"11,30000019","5,800000191","7,800000191",182.0,"0,647000015","0,052000001","0,032000002",NaN,"0,002",1505,1505,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
1,ALFA-ROMEO,159,159,159 1750 Tbi (200ch),M10ALFVP000H341,939BXN1B53C,ES,non,12,147,M 6,"11,5",6,8,186.0,"0,647000015","0,052000001","0,032000002",NaN,"0,002",1555,1555,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
2,ALFA-ROMEO,159,159,159 2.0 JTDm (136ch),M10ALFVP000E302,939AXR1B64,GO,non,7,100,M 6,"6,599999905","4,199999809","5,099999905",134.0,"0,066",NaN,"0,149000004","0,174999997","0,001",1565,1565,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
3,ALFA-ROMEO,159,159,159 2.0 JTDm (136ch),M10ALFVP000F303,939AXR1B64B,GO,non,7,100,M 6,"6,599999905","4,199999809","5,099999905",134.0,"0,066",NaN,"0,149000004","0,174999997","0,001",1565,1565,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN
4,ALFA-ROMEO,159,159,159 2.0 JTDm (170ch),M10ALFVP000G304,939AXS1B66,GO,non,9,125,M 6,"6,900000095","4,300000191","5,300000191",139.0,"0,059999999",NaN,"0,164000005","0,193000004","0,001",1565,1565,715/2007*692/2008EURO5,mars-14,BERLINE,MOY-SUPER,NaN,NaN,NaN,NaN


## Diagnostic des valeurs manquantes

In [21]:

df_2014.shape

(55044, 30)

In [22]:
df_2014.info()

<class 'pandas.DataFrame'>
RangeIndex: 55044 entries, 0 to 55043
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lib_mrq            55044 non-null  str
 1   lib_mod_doss       55044 non-null  str
 2   lib_mod            55044 non-null  str
 3   dscom              55044 non-null  str
 4   cnit               55044 non-null  str
 5   tvv                55044 non-null  str
 6   cod_cbr            55044 non-null  str
 7   hybride            55044 non-null  str
 8   puiss_admin_98     55044 non-null  int64
 9   puiss_max          55044 non-null  str
 10  typ_boite_nb_rapp  55044 non-null  str
 11  conso_urb          55001 non-null  str
 12  conso_exurb        55001 non-null  str
 13  conso_mixte        55010 non-null  str
 14  co2                55010 non-null  float64
 15  co_typ_1           54886 non-null  str
 16  hc                 9773 non-null   str
 17  nox                54886 non-null  str
 18  hcnox              45156 non-null  str
 19  ptcl               52366 non-null  str
 20  masse_ordma_min    55044 non-null  int64
 21  masse_ordma_max    55044 non-null  int64
 22  champ_v9           54983 non-null  str
 23  date_maj           3247 non-null   str
 24  Carrosserie        55044 non-null  str
 25  gamme              55044 non-null  str
 26  Unnamed: 26        0 non-null      float64
 27  Unnamed: 27        0 non-null      float64
 28  Unnamed: 28        0 non-null      float64
 29  Unnamed: 29        0 non-null      float64
dtypes: float64(5), int64(3), str(22)
memory usage: 12.6 MB

In [23]:
(df_2014.isnull().mean() * 100).sort_values(ascending=False)

Unnamed: 27          100.000000
Unnamed: 26          100.000000
Unnamed: 29          100.000000
Unnamed: 28          100.000000
date_maj              94.101083
hc                    82.245113
hcnox                 17.963811
ptcl                   4.865199
nox                    0.287043
co_typ_1               0.287043
champ_v9               0.110820
conso_urb              0.078119
conso_exurb            0.078119
conso_mixte            0.061769
co2                    0.061769
typ_boite_nb_rapp      0.000000
puiss_admin_98         0.000000
hybride                0.000000
cod_cbr                0.000000
dscom                  0.000000
cnit                   0.000000
tvv                    0.000000
lib_mod_doss           0.000000
lib_mrq                0.000000
lib_mod                0.000000
puiss_max              0.000000
masse_ordma_max        0.000000
masse_ordma_min        0.000000
gamme                  0.000000
Carrosserie            0.000000
dtype: float64

## Suppression des colonnes vides et peu exploitables

In [24]:
colonnes_a_supprimer = [
    'Unnamed: 26',
    'Unnamed: 27',
    'Unnamed: 28',
    'Unnamed: 29',
    'date_maj'
]

df_2014 = df_2014.drop(columns=colonnes_a_supprimer)

df_2014.shape

(55044, 25)


Les colonnes `Unnamed: 26` à `Unnamed: 29` ont été supprimées car elles étaient entièrement vides et n'apportaient aucune information exploitable.

La variable `date_maj` a également été retirée du jeu de données. Avec plus de 94 % de valeurs manquantes et sans lien direct avec les caractéristiques techniques des véhicules ou les émissions de CO₂, son exploitation apparaissait peu pertinente pour la suite du projet.

Le dataset passe ainsi de 30 à 25 variables tout en conservant l'ensemble des observations.

In [25]:
df_2014.info()

<class 'pandas.DataFrame'>
RangeIndex: 55044 entries, 0 to 55043
Data columns (total 25 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lib_mrq            55044 non-null  str
 1   lib_mod_doss       55044 non-null  str
 2   lib_mod            55044 non-null  str
 3   dscom              55044 non-null  str
 4   cnit               55044 non-null  str
 5   tvv                55044 non-null  str
 6   cod_cbr            55044 non-null  str
 7   hybride            55044 non-null  str
 8   puiss_admin_98     55044 non-null  int64
 9   puiss_max          55044 non-null  str
 10  typ_boite_nb_rapp  55044 non-null  str
 11  conso_urb          55001 non-null  str
 12  conso_exurb        55001 non-null  str
 13  conso_mixte        55010 non-null  str
 14  co2                55010 non-null  float64
 15  co_typ_1           54886 non-null  str
 16  hc                 9773 non-null   str
 17  nox                54886 non-null  str
 18  hcnox              45156 non-null  str
 19  ptcl               52366 non-null  str
 20  masse_ordma_min    55044 non-null  int64
 21  masse_ordma_max    55044 non-null  int64
 22  champ_v9           54983 non-null  str
 23  Carrosserie        55044 non-null  str
 24  gamme              55044 non-null  str
dtypes: float64(1), int64(3), str(21)
memory usage: 10.5 MB

In [26]:
(df_2014.isnull().mean() * 100).sort_values(ascending=False)

hc                   82.245113
hcnox                17.963811
ptcl                  4.865199
co_typ_1              0.287043
nox                   0.287043
champ_v9              0.110820
conso_exurb           0.078119
conso_urb             0.078119
conso_mixte           0.061769
co2                   0.061769
puiss_admin_98        0.000000
cod_cbr               0.000000
tvv                   0.000000
cnit                  0.000000
dscom                 0.000000
lib_mod               0.000000
lib_mod_doss          0.000000
lib_mrq               0.000000
hybride               0.000000
typ_boite_nb_rapp     0.000000
puiss_max             0.000000
masse_ordma_min       0.000000
masse_ordma_max       0.000000
Carrosserie           0.000000
gamme                 0.000000
dtype: float64

## Suppression de la variable hc

In [27]:
# Suppression de la variable hc

df_2014 = df_2014.drop(columns=['hc'])

df_2014.shape

(55044, 24)

La variable `hc` présente plus de 82 % de valeurs manquantes. Un tel niveau d'absence rend son exploitation difficile et limite fortement sa contribution potentielle à la modélisation.

Compte tenu de son faible taux de complétude, cette variable a été supprimée du jeu de données.

Les variables `hcnox` et `ptcl`, bien qu'incomplètes, ont été conservées car elles disposent encore d'un volume d'information suffisant pour être étudiées lors des étapes suivantes.

In [28]:
df_2014.dtypes

lib_mrq                  str
lib_mod_doss             str
lib_mod                  str
dscom                    str
cnit                     str
tvv                      str
cod_cbr                  str
hybride                  str
puiss_admin_98         int64
puiss_max                str
typ_boite_nb_rapp        str
conso_urb                str
conso_exurb              str
conso_mixte              str
co2                  float64
co_typ_1                 str
nox                      str
hcnox                    str
ptcl                     str
masse_ordma_min        int64
masse_ordma_max        int64
champ_v9                 str
Carrosserie              str
gamme                    str
dtype: object

In [29]:
df_2014[['co_typ_1', 'nox', 'hcnox', 'ptcl']].head()

      co_typ_1          nox        hcnox   ptcl
0  0,647000015  0,032000002          NaN  0,002
1  0,647000015  0,032000002          NaN  0,002
2        0,066  0,149000004  0,174999997  0,001
3        0,066  0,149000004  0,174999997  0,001
4  0,059999999  0,164000005  0,193000004  0,001

In [30]:
df_2014[['co_typ_1', 'nox', 'hcnox', 'ptcl']].dtypes

co_typ_1    str
nox         str
hcnox       str
ptcl        str
dtype: object

In [31]:
df_2014[['puiss_max',
         'conso_urb',
         'conso_exurb',
         'conso_mixte']].head()

  puiss_max    conso_urb  conso_exurb  conso_mixte
0       147  11,30000019  5,800000191  7,800000191
1       147         11,5            6            8
2       100  6,599999905  4,199999809  5,099999905
3       100  6,599999905  4,199999809  5,099999905
4       125  6,900000095  4,300000191  5,300000191

## Conversion des variables numériques

In [32]:
colonnes_numeriques = [
    'puiss_max',
    'conso_urb',
    'conso_exurb',
    'conso_mixte',
    'co_typ_1',
    'nox',
    'hcnox',
    'ptcl'
]

for col in colonnes_numeriques:
    df_2014[col] = (
        df_2014[col]
        .str.replace(',', '.', regex=False)
    )

    df_2014[col] = pd.to_numeric(df_2014[col], errors='coerce')

In [34]:
df_2014.info()

<class 'pandas.DataFrame'>
RangeIndex: 55044 entries, 0 to 55043
Data columns (total 24 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   lib_mrq            55044 non-null  str
 1   lib_mod_doss       55044 non-null  str
 2   lib_mod            55044 non-null  str
 3   dscom              55044 non-null  str
 4   cnit               55044 non-null  str
 5   tvv                55044 non-null  str
 6   cod_cbr            55044 non-null  str
 7   hybride            55044 non-null  str
 8   puiss_admin_98     55044 non-null  int64
 9   puiss_max          55044 non-null  float64
 10  typ_boite_nb_rapp  55044 non-null  str
 11  conso_urb          55001 non-null  float64
 12  conso_exurb        55001 non-null  float64
 13  conso_mixte        55010 non-null  float64
 14  co2                55010 non-null  float64
 15  co_typ_1           54886 non-null  float64
 16  nox                54886 non-null  float64
 17  hcnox              45156 non-null  float64
 18  ptcl               52366 non-null  float64
 19  masse_ordma_min    55044 non-null  int64
 20  masse_ordma_max    55044 non-null  int64
 21  champ_v9           54983 non-null  str
 22  Carrosserie        55044 non-null  str
 23  gamme              55044 non-null  str
dtypes: float64(9), int64(3), str(12)
memory usage: 10.1 MB

In [35]:
(df_2014.isnull().mean() * 100).sort_values(ascending=False)

hcnox                17.963811
ptcl                  4.865199
nox                   0.287043
co_typ_1              0.287043
champ_v9              0.110820
conso_urb             0.078119
conso_exurb           0.078119
conso_mixte           0.061769
co2                   0.061769
cod_cbr               0.000000
tvv                   0.000000
cnit                  0.000000
dscom                 0.000000
lib_mod               0.000000
lib_mod_doss          0.000000
lib_mrq               0.000000
hybride               0.000000
puiss_max             0.000000
typ_boite_nb_rapp     0.000000
puiss_admin_98        0.000000
masse_ordma_min       0.000000
masse_ordma_max       0.000000
Carrosserie           0.000000
gamme                 0.000000
dtype: float64

In [36]:
df_2014[['hcnox', 'ptcl', 'nox', 'co_typ_1']].describe()

              hcnox          ptcl           nox      co_typ_1
count  45156.000000  52366.000000  54886.000000  54886.000000
mean       0.233701      0.000892      0.299160      0.181007
std        0.037490      0.000990      0.416944      0.145014
min        0.000000      0.000000      0.000000      0.005000
25%        0.216000      0.000000      0.197000      0.061000
50%        0.239000      0.001000      0.214000      0.137000
75%        0.253000      0.001000      0.228000      0.297000
max        0.570000      0.023000      1.846000      0.968000

## Suppression de hcnox

In [37]:
df_2014 = df_2014.drop(columns=['hcnox'])

df_2014.shape

(55044, 23)

## Traitement des variables fortement incomplètes

La variable `hcnox` présente près de 18 % de valeurs manquantes. Bien qu'elle soit liée aux émissions polluantes, elle n'apparaît pas parmi les variables les plus influentes dans l'analyse exploratoire.

Afin de limiter les opérations d'imputation sur une variable secondaire et de simplifier le jeu de données, celle-ci a été supprimée.

Les variables `ptcl`, `nox` et `co_typ_1` ont quant à elles été conservées, leur taux de valeurs manquantes restant faible.

In [38]:
df_2014[['ptcl', 'nox', 'co_typ_1']].isnull().sum()

ptcl        2678
nox          158
co_typ_1     158
dtype: int64

## Imputation par la médiane

In [39]:
df_2014['ptcl'] = df_2014['ptcl'].fillna(df_2014['ptcl'].median())

df_2014['nox'] = df_2014['nox'].fillna(df_2014['nox'].median())

df_2014['co_typ_1'] = df_2014['co_typ_1'].fillna(df_2014['co_typ_1'].median())

In [40]:
df_2014[['ptcl', 'nox', 'co_typ_1']].isnull().sum()

ptcl        0
nox         0
co_typ_1    0
dtype: int64

### Imputation des valeurs manquantes

Les variables `ptcl`, `nox` et `co_typ_1` présentent un faible taux de valeurs manquantes, inférieur à 5 %.

Afin de conserver l'ensemble des observations du dataset tout en limitant l'impact des valeurs extrêmes, les données manquantes ont été remplacées par la médiane de chaque variable.

Cette méthode est particulièrement adaptée aux variables quantitatives dont la distribution peut être asymétrique et permet de préserver la robustesse des analyses futures.

In [41]:
df_2014.isnull().sum().sort_values(ascending=False).head(10)

champ_v9        61
conso_exurb     43
conso_urb       43
co2             34
conso_mixte     34
lib_mod_doss     0
lib_mrq          0
cod_cbr          0
tvv              0
cnit             0
dtype: int64

## Supprimer les lignes où le CO₂ est manquant

In [42]:
df_2014 = df_2014.dropna(subset=['co2'])

In [43]:
df_2014.isnull().sum().sort_values(ascending=False).head(10)

champ_v9        27
conso_exurb      9
conso_urb        9
dscom            0
lib_mrq          0
lib_mod_doss     0
lib_mod          0
cod_cbr          0
tvv              0
cnit             0
dtype: int64

In [45]:
df_2014['champ_v9'].value_counts(dropna=False)

champ_v9
"715/2007*692/2008EURO5    23979
"715/2007*195/2013EURO5    14821
"715/2007*566/2011EURO5     4851
"2005/55*2008/74EURO5       1864
"2005/55*2008/74EEV         1830
"715/2007*195/2013EURO6     1652
"715/2007*630/2012EURO5     1349
715/2007*630/2012EURO5       824
715/2007*692/2008EURO5       769
715/2007*195/2013EURO5       722
"595/2009*64/2012EURO6       604
"715/2007*630/2012EURO6      353
715/2007*566/2011EURO5       338
"715/2007*459/2012EURO5      325
715/2007*195/2013EURO6       278
715/2007*630/2012EURO6       132
"715/2007*143/2013EURO6      104
715/2007*459/2012EURO5        80
"715/2007*143/2013EURO5       34
NaN                           27
"715/2007*566/2011EURO6       20
"715/2007*459/2012EURO6       11
715/2007*143/2013EURO5         9
715/2007*459/2012EURO6         6
715/2007*630/2012EURO          6
715/2007*195/20                5
715/2007*1                     3
715/2007*195/2013EUR           2
715/2007*                      2
715/2007*630/20                2
715/20                         2
715/2007*459/2012EURO          2
715/2007*195/2013EU            1
715/2007*195/201               1
715/2007*195/2013              1
715/2007*459/2012EU            1
Name: count, dtype: int64

In [46]:
df_2014 = df_2014.dropna()

df_2014.isnull().sum().sum()

np.int64(0)

### Finalisation du traitement des valeurs manquantes

Après les différentes opérations de nettoyage et d'imputation, seules 27 observations présentaient encore une valeur manquante sur la variable `champ_v9`.

Compte tenu du très faible nombre d'observations concernées (moins de 0,05 % du dataset), ces lignes ont été supprimées.

Le jeu de données final ne contient ainsi plus aucune valeur manquante et est désormais prêt pour les étapes de transformation et de modélisation.

## État final du dataset après pré-processing

In [47]:
df_2014.shape

(54974, 23)

Le dataset final contient 54 974 observations et 23 variables après les différentes étapes de pré-processing.

Les colonnes vides ou fortement incomplètes (`Unnamed`, `date_maj`, `hc` et `hcnox`) ont été supprimées. Les variables numériques stockées sous forme de texte ont été converties au format approprié et les valeurs manquantes ont été traitées par suppression ou imputation lorsque cela était nécessaire.

Le jeu de données est désormais propre, cohérent et prêt pour les étapes de transformation des variables et de modélisation des émissions de CO₂.